@Tracker.Api_HostAddress = http://localhost:5041/api/expense

### Create Expense
POST {{Tracker.Api_HostAddress}}
Content-Type: application/json

{
  "UserId": "019465cb-0e37-7fc3-903e-9faadb519690",
  "Amount": "10",
  "Unit": "lkr",
  "Date": "2025-01-14",
  "Description": "reload"
}

### Delete Expense
Delete {{Tracker.Api_HostAddress}}/019465a6-da65-7328-bed1-2cdad1323d94
Content-Type: application/json
